/**
 * Enum di supporto che definisce il cod_stato_elabora.
 */
export enum CodiciStatiElaborazione {
  EMISSIONE_RICHIESTA = 'EMRICH',
  EMESSA = 'EMESS',
  EMESSA_KO = 'EMESS_KO',
  CONFERMA_RICHIESTA = 'CONFRICH',
  TERMINATA = 'TERMIN',
  TERMINATA_KO = 'TERMIN_KO',
  ANNULLATA = 'ANNULL',
  ATTESA_IUV = 'ATTESAIUV',
  IUV_OK = 'IUVOK',
  ATTESA_PDF = 'ATTESAPDF',
  PDF_PRONTI = 'PDFPRONTI',
  PDF_OK = 'PDFOK',
  MAIL_OK = 'MAILOK',
  ANNULLA_RICHIESTA = 'ANNULLRICH',
  ANNULLATA_KO = 'ANNULL_KO',
  INVIO_ACTA_COMPLETATO = 'INVACTA_OK',
  INVIO_ACTA_ARCHIVIATO = 'INVACTA_AR',
  INVIO_ACTA_AVVIO = 'INVACTA_ON',
  INVIO_ACTA_PARZIALE = 'INVACTA_KO',
  PAGAM_PAGOPA_AVVIO = 'PAGPGPA_ON',
  PAGAM_PAGOPA_OK = 'PAGPGPA_OK',
  PAGAM_PAGOPA_KO = 'PAGPPGA_KO',
  TXT_PRONTI = 'TXTPRONTI',
}

/**
 * Enum di supporto che definisce l'id_stato_elabora.
 */
export enum IdStatiElaborazione {
  EMISSIONE_RICHIESTA = 1,
  EMESSA = 2,
  EMESSA_KO = 3,
  CONFERMA_RICHIESTA = 4,
  TERMINATA = 5,
  TERMINATA_KO = 6,
  ANNULLATA = 7,
  ATTESA_IUV = 8,
  IUV_OK = 9,
  ATTESA_PDF = 10,
  PDF_PRONTI = 11,
  PDF_OK = 12,
  MAIL_OK = 13,
  ANNULLA_RICHIESTA = 14,
  ANNULLATA_KO = 15,
  INVIO_ACTA_COMPLETATO = 18,
  INVIO_ACTA_ARCHIVIATO = 19,
  INVIO_ACTA_AVVIO = 16,
  INVIO_ACTA_PARZIALE = 17,
  PAGAM_PAGOPA_AVVIO = 20,
  PAGAM_PAGOPA_OK = 21,
  PAGAM_PAGOPA_KO = 22,
  TXT_PRONTI = 23,
}
