/*******************************************************************************
 *  ========================LICENSE_START=================================
 *   
 *  Copyright (C) 2025 Regione Piemonte
 *   
 *  SPDX-FileCopyrightText: (C) Copyright 2025  Regione Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 *  =========================LICENSE_END==================================
 *******************************************************************************/
/**
 * OfficialBookServicePort_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package it.csi.risca.riscabesrv.util.actaofficialbook;

public interface OfficialBookServicePort_PortType extends java.rmi.Remote {
    public it.csi.risca.riscabesrv.util.actaofficialbook.IdentificazioneRegistrazione creaRegistrazione(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, java.lang.String tipologiaCreazione, it.csi.risca.riscabesrv.util.actaofficialbook.RegistrazioneRequest infoRichiestaCreazione) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaofficialbook.IdentificazioneRegistrazione importaRegistrazione(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType classificazioneId, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType registroId, it.csi.risca.riscabesrv.util.actaofficialbook.InfoRegistrazione infoRegistrazione, boolean senzaCreazioneSoggetti) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaofficialbook.PagingResponseType getRegistries(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType aooId, java.lang.Integer anno, it.csi.risca.riscabesrv.util.actaofficialbook.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaofficialbook.ObjectResponseType getProperties(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType objectId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaofficialbook.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaofficialbook.SimpleResponseType updateProperties(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType objectId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaofficialbook.ChangeTokenType changeToken, it.csi.risca.riscabesrv.util.actaofficialbook.PropertyType[] properties) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaofficialbook.PagingResponseType query(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaofficialbook.QueryableObjectType target, it.csi.risca.riscabesrv.util.actaofficialbook.PropertyFilterType filter, it.csi.risca.riscabesrv.util.actaofficialbook.QueryConditionType[] criteria, it.csi.risca.riscabesrv.util.actaofficialbook.NavigationConditionInfoType navigationLimits, java.lang.Integer maxItems, java.lang.Integer skipCount) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaofficialbook.ObjectResponseType[] getPropertiesMassive(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType[] identifiers, it.csi.risca.riscabesrv.util.actaofficialbook.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaofficialbook.IdentificazioneAnnotazioneOB creaAnnotazioneOB(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType target, java.lang.String tipologiaTarget, it.csi.risca.riscabesrv.util.actaofficialbook.PropertiesType properties) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public void inviaSegnatura(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, java.lang.String origine, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType identificatoreRegistraizone, it.csi.risca.riscabesrv.util.actaofficialbook.InfoMittenteIS mittente, it.csi.risca.riscabesrv.util.actaofficialbook.InfoDestinatarioIS[] destinatari, java.lang.String identitaDigitale) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType inviaSegnaturaRegistrazione(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType identificatoreRegistrazione, it.csi.risca.riscabesrv.util.actaofficialbook.InfoMittenteIS mittente, it.csi.risca.riscabesrv.util.actaofficialbook.InfoDestinatarioRegistrazione[] destinatari, it.csi.risca.riscabesrv.util.actaofficialbook.InfoInvioSegnatura info) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaofficialbook.DatiInterscambioResponseType ricercaDatiInterscambio(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType identificatoreRegistrazione, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType identificatoreSegnatura, java.lang.String tipoMessaggio, java.lang.Integer maxItems, java.lang.Integer skipCount) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaofficialbook.SimpleResponseType annullaRegistrazione(it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaofficialbook.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaofficialbook.ObjectIdType identificatoreRegistrazione, java.lang.String motivazione) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaofficialbook.AcarisFaultType;
}
