/* *****************************************************
 * Copyright Regione Piemonte - 2025
 * SPDX-License-Identifier: EUPL-1.2-or-later
 ******************************************************/

CREATE SEQUENCE seq_risca_cod_gruppo_soggetto              INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_ambito_area_competenza         INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_ambito_interesse               INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_annualita_sd                   INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_annualita_uso_sd               INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_annualita_uso_sd_ra            INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_dettaglio_pag                  INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_dettaglio_pag_bil_acc          INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_gruppo_delega                  INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_iuv_da_inviare                 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_pag_non_propri                 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_pagopa_lista_car_iuv           INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_pagopa_lista_carico            INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_pagopa_scomp_rich_iuv          INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_pagopa_scomp_var_iuv           INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_parametro_elabora              INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_provvedimento                  INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_rata_sd                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_recapito                       INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_recapito_postel                INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_registro_elabora               INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_rimborso                       INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_riscossione_storia_titolare    INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_riscossione_uso                INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_ruolo                          INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_ruolo_soris_fr1                INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_ruolo_soris_fr3                INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_ruolo_soris_fr7                INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_soggetto_delega                INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_soll_dati_amministr            INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_soll_dati_pagopa               INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_soll_dati_titolare             INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_soll_destinatari               INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_soll_dett_vers                 INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_spedizione_acta                INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_tipo_uso_regola                INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_r_uso_ridaum                     INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_s_tracciamento                   INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_accertamento                   INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_delegato                       INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_elabora                        INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_file_450                       INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_file_poste                     INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_file_soris                     INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_gruppo_soggetto                INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_immagine                       INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_invio_acta                     INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_iuv                            INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_lotto                          INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_pagamento                      INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_riscossione                    INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_soggetto                       INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_spedizione                     INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;
CREATE SEQUENCE seq_risca_t_stato_debitorio                INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999 START 1;


ALTER SEQUENCE seq_risca_cod_gruppo_soggetto             OWNER TO risca;
ALTER SEQUENCE seq_risca_r_ambito_area_competenza        OWNER TO risca;
ALTER SEQUENCE seq_risca_r_ambito_interesse              OWNER TO risca;
ALTER SEQUENCE seq_risca_r_annualita_sd                  OWNER TO risca;
ALTER SEQUENCE seq_risca_r_annualita_uso_sd              OWNER TO risca;
ALTER SEQUENCE seq_risca_r_annualita_uso_sd_ra           OWNER TO risca;
ALTER SEQUENCE seq_risca_r_dettaglio_pag                 OWNER TO risca;
ALTER SEQUENCE seq_risca_r_dettaglio_pag_bil_acc         OWNER TO risca;
ALTER SEQUENCE seq_risca_r_gruppo_delega                 OWNER TO risca;
ALTER SEQUENCE seq_risca_r_iuv_da_inviare                OWNER TO risca;
ALTER SEQUENCE seq_risca_r_pag_non_propri                OWNER TO risca;
ALTER SEQUENCE seq_risca_r_pagopa_lista_car_iuv          OWNER TO risca;
ALTER SEQUENCE seq_risca_r_pagopa_lista_carico           OWNER TO risca;
ALTER SEQUENCE seq_risca_r_pagopa_scomp_rich_iuv         OWNER TO risca;
ALTER SEQUENCE seq_risca_r_pagopa_scomp_var_iuv          OWNER TO risca;
ALTER SEQUENCE seq_risca_r_parametro_elabora             OWNER TO risca;
ALTER SEQUENCE seq_risca_r_provvedimento                 OWNER TO risca;
ALTER SEQUENCE seq_risca_r_rata_sd                       OWNER TO risca;
ALTER SEQUENCE seq_risca_r_recapito                      OWNER TO risca;
ALTER SEQUENCE seq_risca_r_recapito_postel               OWNER TO risca;
ALTER SEQUENCE seq_risca_r_registro_elabora              OWNER TO risca;
ALTER SEQUENCE seq_risca_r_rimborso                      OWNER TO risca;
ALTER SEQUENCE seq_risca_r_riscossione_storia_titolare   OWNER TO risca;
ALTER SEQUENCE seq_risca_r_riscossione_uso               OWNER TO risca;
ALTER SEQUENCE seq_risca_r_ruolo                         OWNER TO risca;
ALTER SEQUENCE seq_risca_r_ruolo_soris_fr1               OWNER TO risca;
ALTER SEQUENCE seq_risca_r_ruolo_soris_fr3               OWNER TO risca;
ALTER SEQUENCE seq_risca_r_ruolo_soris_fr7               OWNER TO risca;
ALTER SEQUENCE seq_risca_r_soggetto_delega               OWNER TO risca;
ALTER SEQUENCE seq_risca_r_soll_dati_amministr           OWNER TO risca;
ALTER SEQUENCE seq_risca_r_soll_dati_pagopa              OWNER TO risca;
ALTER SEQUENCE seq_risca_r_soll_dati_titolare            OWNER TO risca;
ALTER SEQUENCE seq_risca_r_soll_destinatari              OWNER TO risca;
ALTER SEQUENCE seq_risca_r_soll_dett_vers                OWNER TO risca;
ALTER SEQUENCE seq_risca_r_spedizione_acta               OWNER TO risca;
ALTER SEQUENCE seq_risca_r_tipo_uso_regola               OWNER TO risca;
ALTER SEQUENCE seq_risca_r_uso_ridaum                    OWNER TO risca;
ALTER SEQUENCE seq_risca_s_tracciamento                  OWNER TO risca;
ALTER SEQUENCE seq_risca_t_accertamento                  OWNER TO risca;
ALTER SEQUENCE seq_risca_t_delegato                      OWNER TO risca;
ALTER SEQUENCE seq_risca_t_elabora                       OWNER TO risca;
ALTER SEQUENCE seq_risca_t_file_450                      OWNER TO risca;
ALTER SEQUENCE seq_risca_t_file_poste                    OWNER TO risca;
ALTER SEQUENCE seq_risca_t_file_soris                    OWNER TO risca;
ALTER SEQUENCE seq_risca_t_gruppo_soggetto               OWNER TO risca;
ALTER SEQUENCE seq_risca_t_immagine                      OWNER TO risca;
ALTER SEQUENCE seq_risca_t_invio_acta                    OWNER TO risca;
ALTER SEQUENCE seq_risca_t_iuv                           OWNER TO risca;
ALTER SEQUENCE seq_risca_t_lotto                         OWNER TO risca;
ALTER SEQUENCE seq_risca_t_pagamento                     OWNER TO risca;
ALTER SEQUENCE seq_risca_t_riscossione                   OWNER TO risca;
ALTER SEQUENCE seq_risca_t_soggetto                      OWNER TO risca;
ALTER SEQUENCE seq_risca_t_spedizione                    OWNER TO risca;
ALTER SEQUENCE seq_risca_t_stato_debitorio               OWNER TO risca;

GRANT ALL ON SEQUENCE seq_risca_cod_gruppo_soggetto             TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_ambito_area_competenza        TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_ambito_interesse              TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_annualita_sd                  TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_annualita_uso_sd              TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_annualita_uso_sd_ra           TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_dettaglio_pag                 TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_dettaglio_pag_bil_acc         TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_gruppo_delega                 TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_iuv_da_inviare                TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_pag_non_propri                TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_pagopa_lista_car_iuv          TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_pagopa_lista_carico           TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_pagopa_scomp_rich_iuv         TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_pagopa_scomp_var_iuv          TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_parametro_elabora             TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_provvedimento                 TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_rata_sd                       TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_recapito                      TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_recapito_postel               TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_registro_elabora              TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_rimborso                      TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_riscossione_storia_titolare   TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_riscossione_uso               TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_ruolo                         TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_ruolo_soris_fr1               TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_ruolo_soris_fr3               TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_ruolo_soris_fr7               TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_soggetto_delega               TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_soll_dati_amministr           TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_soll_dati_pagopa              TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_soll_dati_titolare            TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_soll_destinatari              TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_soll_dett_vers                TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_spedizione_acta               TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_tipo_uso_regola               TO risca;
GRANT ALL ON SEQUENCE seq_risca_r_uso_ridaum                    TO risca;
GRANT ALL ON SEQUENCE seq_risca_s_tracciamento                  TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_accertamento                  TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_delegato                      TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_elabora                       TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_file_450                      TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_file_poste                    TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_file_soris                    TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_gruppo_soggetto               TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_immagine                      TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_invio_acta                    TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_iuv                           TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_lotto                         TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_pagamento                     TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_riscossione                   TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_soggetto                      TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_spedizione                    TO risca;
GRANT ALL ON SEQUENCE seq_risca_t_stato_debitorio               TO risca;

GRANT ALL ON SEQUENCE seq_risca_cod_gruppo_soggetto             TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_ambito_area_competenza        TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_ambito_interesse              TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_annualita_sd                  TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_annualita_uso_sd              TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_annualita_uso_sd_ra           TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_dettaglio_pag                 TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_dettaglio_pag_bil_acc         TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_gruppo_delega                 TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_iuv_da_inviare                TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_pag_non_propri                TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_pagopa_lista_car_iuv          TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_pagopa_lista_carico           TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_pagopa_scomp_rich_iuv         TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_pagopa_scomp_var_iuv          TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_parametro_elabora             TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_provvedimento                 TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_rata_sd                       TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_recapito                      TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_recapito_postel               TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_registro_elabora              TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_rimborso                      TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_riscossione_storia_titolare   TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_riscossione_uso               TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_ruolo                         TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_ruolo_soris_fr1               TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_ruolo_soris_fr3               TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_ruolo_soris_fr7               TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_soggetto_delega               TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_soll_dati_amministr           TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_soll_dati_pagopa              TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_soll_dati_titolare            TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_soll_destinatari              TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_soll_dett_vers                TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_spedizione_acta               TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_tipo_uso_regola               TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_r_uso_ridaum                    TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_s_tracciamento                  TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_accertamento                  TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_delegato                      TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_elabora                       TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_file_450                      TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_file_poste                    TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_file_soris                    TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_gruppo_soggetto               TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_immagine                      TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_invio_acta                    TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_iuv                           TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_lotto                         TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_pagamento                     TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_riscossione                   TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_soggetto                      TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_spedizione                    TO risca_rw;
GRANT ALL ON SEQUENCE seq_risca_t_stato_debitorio               TO risca_rw;
