/* *****************************************************
 * Copyright Regione Piemonte - 2025
 * SPDX-License-Identifier: EUPL-1.2-or-later
 ******************************************************/

-- Views
DROP VIEW IF EXISTS v_archiviazione_acta_bonari_solleciti;
DROP VIEW IF EXISTS v_archiviazione_acta_ordinaria_speciale;
DROP VIEW IF EXISTS v_report_bilancio_altri_pagamenti;
DROP VIEW IF EXISTS v_report_bilancio_dettagli_bil_acc;
DROP VIEW IF EXISTS v_riscossioni_bollettazione_ordinaria;
DROP VIEW IF EXISTS v_riscossioni_bollettazione_speciale;
DROP VIEW IF EXISTS v_riscossioni_report_ricerca;
DROP VIEW IF EXISTS v_stati_debitori_avvisi_e_solleciti;
DROP VIEW IF EXISTS v_utility_lista_pagamenti_sd;
DROP VIEW IF EXISTS v_utility_lista_provvedimenti;
DROP VIEW IF EXISTS v_utility_lista_riscossioni;
DROP VIEW IF EXISTS v_utility_lista_stati_debitori;
DROP VIEW IF EXISTS v_utility_lista_usi_riscossione;


-- Functions
DROP FUNCTION IF EXISTS utility_fnc_aggiorna_sequence()               CASCADE;
DROP FUNCTION IF EXISTS utility_fnc_check_elaborazione()              CASCADE;
DROP FUNCTION IF EXISTS utility_fnc_check_riscossioni()               CASCADE;
DROP FUNCTION IF EXISTS utility_fnc_delete_file_450()                 CASCADE;
DROP FUNCTION IF EXISTS utility_fnc_delete_file_450_nosd()            CASCADE;
DROP FUNCTION IF EXISTS utility_fnc_delete_riscossione()              CASCADE;
DROP FUNCTION IF EXISTS utility_fnc_delete_stato_debitorio()          CASCADE;
DROP FUNCTION IF EXISTS utility_fnc_ricerca_riscossione_json_dt()     CASCADE;


-- Tables
DROP TABLE IF EXISTS csi_log_audit                           CASCADE;
DROP TABLE IF EXISTS risca_d_accerta_bilancio                CASCADE;
DROP TABLE IF EXISTS risca_d_algoritmo                       CASCADE;
DROP TABLE IF EXISTS risca_d_ambito                          CASCADE;
DROP TABLE IF EXISTS risca_d_attivita_stato_deb              CASCADE;
DROP TABLE IF EXISTS risca_d_componente_dt                   CASCADE;
DROP TABLE IF EXISTS risca_d_comune                          CASCADE;
DROP TABLE IF EXISTS risca_d_configurazione                  CASCADE;
DROP TABLE IF EXISTS risca_d_continente                      CASCADE;
DROP TABLE IF EXISTS risca_d_dato_tecnico                    CASCADE;
DROP TABLE IF EXISTS risca_d_email_servizio                  CASCADE;
DROP TABLE IF EXISTS risca_d_email_standard                  CASCADE;
DROP TABLE IF EXISTS risca_d_ente_pagopa                     CASCADE;
DROP TABLE IF EXISTS risca_d_fase_elabora                    CASCADE;
DROP TABLE IF EXISTS risca_d_fonte                           CASCADE;
DROP TABLE IF EXISTS risca_d_funzionalita                    CASCADE;
DROP TABLE IF EXISTS risca_d_mappa_fonte_esterna             CASCADE;
DROP TABLE IF EXISTS risca_d_messaggio                       CASCADE;
DROP TABLE IF EXISTS risca_d_nazione                         CASCADE;
DROP TABLE IF EXISTS risca_d_oggetto_app                     CASCADE;
DROP TABLE IF EXISTS risca_d_origine_limiti                  CASCADE;
DROP TABLE IF EXISTS risca_d_output_colonna                  CASCADE;
DROP TABLE IF EXISTS risca_d_output_file                     CASCADE;
DROP TABLE IF EXISTS risca_d_output_foglio                   CASCADE;
DROP TABLE IF EXISTS risca_d_passo_elabora                   CASCADE;
DROP TABLE IF EXISTS risca_d_profilo_pa                      CASCADE;
DROP TABLE IF EXISTS risca_d_provincia                       CASCADE;
DROP TABLE IF EXISTS risca_d_regione                         CASCADE;
DROP TABLE IF EXISTS risca_d_riduzione_aumento               CASCADE;
DROP TABLE IF EXISTS risca_d_sigla_personale                 CASCADE;
DROP TABLE IF EXISTS risca_d_stato_contribuzione             CASCADE;
DROP TABLE IF EXISTS risca_d_stato_elabora                   CASCADE;
DROP TABLE IF EXISTS risca_d_stato_iuv                       CASCADE;
DROP TABLE IF EXISTS risca_d_stato_riscossione               CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_accertamento               CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_area_competenza            CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_attivita_stato_deb         CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_autorizza                  CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_componente_dt              CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_dato_colonna               CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_dato_tecnico               CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_dilazione                  CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_elabora                    CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_imp_non_propri             CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_invio                      CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_messaggio                  CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_modalita_pag               CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_natura_giuridica           CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_oggetto_app                CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_passo_elabora              CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_personale                  CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_provvedimento              CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_recapito                   CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_ricerca_morosita           CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_ricerca_pagamento          CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_ricerca_rimborso           CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_rimborso                   CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_riscossione                CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_sede                       CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_soggetto                   CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_spedizione                 CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_titolo                     CASCADE;
DROP TABLE IF EXISTS risca_d_tipo_uso                        CASCADE;
DROP TABLE IF EXISTS risca_d_tipologia_pag                   CASCADE;
DROP TABLE IF EXISTS risca_d_unita_misura                    CASCADE;
DROP TABLE IF EXISTS risca_r_ambito_area_competenza          CASCADE;
DROP TABLE IF EXISTS risca_r_ambito_config                   CASCADE;
DROP TABLE IF EXISTS risca_r_ambito_fonte                    CASCADE;
DROP TABLE IF EXISTS risca_r_ambito_interesse                CASCADE;
DROP TABLE IF EXISTS risca_r_ambito_provincia                CASCADE;
DROP TABLE IF EXISTS risca_r_annualita_sd                    CASCADE;
DROP TABLE IF EXISTS risca_r_annualita_uso_sd                CASCADE;
DROP TABLE IF EXISTS risca_r_annualita_uso_sd_ra             CASCADE;
DROP TABLE IF EXISTS risca_r_avviso_annualita                CASCADE;
DROP TABLE IF EXISTS risca_r_avviso_dati_ammin               CASCADE;
DROP TABLE IF EXISTS risca_r_avviso_dati_titolare            CASCADE;
DROP TABLE IF EXISTS risca_r_avviso_uso                      CASCADE;
DROP TABLE IF EXISTS risca_r_dettaglio_pag                   CASCADE;
DROP TABLE IF EXISTS risca_r_dettaglio_pag_bil_acc           CASCADE;
DROP TABLE IF EXISTS risca_r_dt_valore_ammesso               CASCADE;
DROP TABLE IF EXISTS risca_r_email_st_punti_valori           CASCADE;
DROP TABLE IF EXISTS risca_r_email_st_segnaposto             CASCADE;
DROP TABLE IF EXISTS risca_r_etichetta                       CASCADE;
DROP TABLE IF EXISTS risca_r_funzionalita_stato              CASCADE;
DROP TABLE IF EXISTS risca_r_gruppo_delega                   CASCADE;
DROP TABLE IF EXISTS risca_r_iuv_da_inviare                  CASCADE;
DROP TABLE IF EXISTS risca_r_iuv_da_inviare_2024_12_11       CASCADE;
DROP TABLE IF EXISTS risca_r_pag_non_propri                  CASCADE;
DROP TABLE IF EXISTS risca_r_pag_non_propri_2024_04_09       CASCADE;
DROP TABLE IF EXISTS risca_r_pagopa_lista_car_iuv            CASCADE;
DROP TABLE IF EXISTS risca_r_pagopa_lista_carico             CASCADE;
DROP TABLE IF EXISTS risca_r_pagopa_scomp_rich_iuv           CASCADE;
DROP TABLE IF EXISTS risca_r_pagopa_scomp_var_iuv            CASCADE;
DROP TABLE IF EXISTS risca_r_parametro_elabora               CASCADE;
DROP TABLE IF EXISTS risca_r_profilo_ogg_app                 CASCADE;
DROP TABLE IF EXISTS risca_r_provvedimento                   CASCADE;
DROP TABLE IF EXISTS risca_r_rata_sd                         CASCADE;
DROP TABLE IF EXISTS risca_r_rata_sd_2024_03_04              CASCADE;
DROP TABLE IF EXISTS risca_r_recapito                        CASCADE;
DROP TABLE IF EXISTS risca_r_recapito_postel                 CASCADE;
DROP TABLE IF EXISTS risca_r_registro_elabora                CASCADE;
DROP TABLE IF EXISTS risca_r_rimborso                        CASCADE;
DROP TABLE IF EXISTS risca_r_rimborso_sd_utilizzato          CASCADE;
DROP TABLE IF EXISTS risca_r_riscossione_recapito            CASCADE;
DROP TABLE IF EXISTS risca_r_riscossione_storia_titolare     CASCADE;
DROP TABLE IF EXISTS risca_r_riscossione_uso                 CASCADE;
DROP TABLE IF EXISTS risca_r_ruolo                           CASCADE;
DROP TABLE IF EXISTS risca_r_ruolo_soris_fr1                 CASCADE;
DROP TABLE IF EXISTS risca_r_ruolo_soris_fr3                 CASCADE;
DROP TABLE IF EXISTS risca_r_ruolo_soris_fr7                 CASCADE;
DROP TABLE IF EXISTS risca_r_soggetto_delega                 CASCADE;
DROP TABLE IF EXISTS risca_r_soggetto_gruppo                 CASCADE;
DROP TABLE IF EXISTS risca_r_soll_dati_amministr             CASCADE;
DROP TABLE IF EXISTS risca_r_soll_dati_pagopa                CASCADE;
DROP TABLE IF EXISTS risca_r_soll_dati_titolare              CASCADE;
DROP TABLE IF EXISTS risca_r_soll_destinatari                CASCADE;
DROP TABLE IF EXISTS risca_r_soll_dett_vers                  CASCADE;
DROP TABLE IF EXISTS risca_r_spedizione_acta                 CASCADE;
DROP TABLE IF EXISTS risca_r_terna_prod_energ                CASCADE;
DROP TABLE IF EXISTS risca_r_tipo_ricerca_mor_accerta        CASCADE;
DROP TABLE IF EXISTS risca_r_tipo_sede_accertamento          CASCADE;
DROP TABLE IF EXISTS risca_r_tipo_uso_dt                     CASCADE;
DROP TABLE IF EXISTS risca_r_tipo_uso_regola                 CASCADE;
DROP TABLE IF EXISTS risca_r_tipo_uso_ridaum                 CASCADE;
DROP TABLE IF EXISTS risca_r_uso_ridaum                      CASCADE;
DROP TABLE IF EXISTS risca_s_comune                          CASCADE;
DROP TABLE IF EXISTS risca_s_nazione                         CASCADE;
DROP TABLE IF EXISTS risca_s_provincia                       CASCADE;
DROP TABLE IF EXISTS risca_s_regione                         CASCADE;
DROP TABLE IF EXISTS risca_s_tracciamento                    CASCADE;
DROP TABLE IF EXISTS risca_t_accertamento                    CASCADE;
DROP TABLE IF EXISTS risca_t_avviso_pagamento                CASCADE;
DROP TABLE IF EXISTS risca_t_bil_acc                         CASCADE;
DROP TABLE IF EXISTS risca_t_delegato                        CASCADE;
DROP TABLE IF EXISTS risca_t_elabora                         CASCADE;
DROP TABLE IF EXISTS risca_t_file_450                        CASCADE;
DROP TABLE IF EXISTS risca_t_file_poste                      CASCADE;
DROP TABLE IF EXISTS risca_t_file_soris                      CASCADE;
DROP TABLE IF EXISTS risca_t_gruppo_soggetto                 CASCADE;
DROP TABLE IF EXISTS risca_t_immagine                        CASCADE;
DROP TABLE IF EXISTS risca_t_invio_acta                      CASCADE;
DROP TABLE IF EXISTS risca_t_iuv                             CASCADE;
DROP TABLE IF EXISTS risca_t_lotto                           CASCADE;
DROP TABLE IF EXISTS risca_t_pagamento                       CASCADE;
DROP TABLE IF EXISTS risca_t_riscossione                     CASCADE;
DROP TABLE IF EXISTS risca_t_soggetto                        CASCADE;
DROP TABLE IF EXISTS risca_t_spedizione                      CASCADE;
DROP TABLE IF EXISTS risca_t_stato_debitorio                 CASCADE;
DROP TABLE IF EXISTS risca_t_terna_prezzi_energ              CASCADE;
DROP TABLE IF EXISTS risca_t_terna_utenze                    CASCADE;
DROP TABLE IF EXISTS risca_w_accertamento                    CASCADE;
DROP TABLE IF EXISTS risca_w_annualita_sd                    CASCADE;
DROP TABLE IF EXISTS risca_w_annualita_uso_sd                CASCADE;
DROP TABLE IF EXISTS risca_w_annualita_uso_sd_ra             CASCADE;
DROP TABLE IF EXISTS risca_w_avviso_annualita                CASCADE;
DROP TABLE IF EXISTS risca_w_avviso_dati_ammin               CASCADE;
DROP TABLE IF EXISTS risca_w_avviso_dati_titolare            CASCADE;
DROP TABLE IF EXISTS risca_w_avviso_pagamento                CASCADE;
DROP TABLE IF EXISTS risca_w_avviso_uso                      CASCADE;
DROP TABLE IF EXISTS risca_w_lock_riscossione                CASCADE;
DROP TABLE IF EXISTS risca_w_output_dati                     CASCADE;
DROP TABLE IF EXISTS risca_w_pagopa_scomp_rich_iuv           CASCADE;
DROP TABLE IF EXISTS risca_w_pagopa_scomp_var_iuv            CASCADE;
DROP TABLE IF EXISTS risca_w_rata_sd                         CASCADE;
DROP TABLE IF EXISTS risca_w_rimborso_sd_utilizzato          CASCADE;
DROP TABLE IF EXISTS risca_w_rimborso_upd                    CASCADE;
DROP TABLE IF EXISTS risca_w_rp_estrco                       CASCADE;
DROP TABLE IF EXISTS risca_w_rp_nonpremarcati                CASCADE;
DROP TABLE IF EXISTS risca_w_rp_pagopa                       CASCADE;
DROP TABLE IF EXISTS risca_w_soll_dati_amministr             CASCADE;
DROP TABLE IF EXISTS risca_w_soll_dati_pagopa                CASCADE;
DROP TABLE IF EXISTS risca_w_soll_dati_titolare              CASCADE;
DROP TABLE IF EXISTS risca_w_soll_destinatari                CASCADE;
DROP TABLE IF EXISTS risca_w_soll_dett_vers                  CASCADE;
DROP TABLE IF EXISTS risca_w_soris_00c                       CASCADE;
DROP TABLE IF EXISTS risca_w_soris_99c                       CASCADE;
DROP TABLE IF EXISTS risca_w_soris_fr0                       CASCADE;
DROP TABLE IF EXISTS risca_w_soris_fr1                       CASCADE;
DROP TABLE IF EXISTS risca_w_soris_fr2                       CASCADE;
DROP TABLE IF EXISTS risca_w_soris_fr3                       CASCADE;
DROP TABLE IF EXISTS risca_w_soris_fr3_pag_da_inserire       CASCADE;
DROP TABLE IF EXISTS risca_w_soris_fr3_r_pag_sd              CASCADE;
DROP TABLE IF EXISTS risca_w_soris_fr7                       CASCADE;
DROP TABLE IF EXISTS risca_w_spedizione                      CASCADE;
DROP TABLE IF EXISTS risca_w_stato_debitorio                 CASCADE;
DROP TABLE IF EXISTS risca_w_stato_debitorio_upd             CASCADE;
DROP TABLE IF EXISTS risca_w_terna_prezzi_energ              CASCADE;
DROP TABLE IF EXISTS risca_w_terna_prod_energ                CASCADE;
DROP TABLE IF EXISTS risca_w_terna_prod_energ_xls            CASCADE;
DROP TABLE IF EXISTS risca_w_terna_utenze                    CASCADE;


-- Sequuences
DROP SEQUENCE IF EXISTS seq_risca_cod_gruppo_soggetto;
DROP SEQUENCE IF EXISTS seq_risca_r_ambito_area_competenza;
DROP SEQUENCE IF EXISTS seq_risca_r_ambito_interesse;
DROP SEQUENCE IF EXISTS seq_risca_r_annualita_sd;
DROP SEQUENCE IF EXISTS seq_risca_r_annualita_uso_sd;
DROP SEQUENCE IF EXISTS seq_risca_r_annualita_uso_sd_ra;
DROP SEQUENCE IF EXISTS seq_risca_r_dettaglio_pag;
DROP SEQUENCE IF EXISTS seq_risca_r_dettaglio_pag_bil_acc;
DROP SEQUENCE IF EXISTS seq_risca_r_gruppo_delega;
DROP SEQUENCE IF EXISTS seq_risca_r_iuv_da_inviare;
DROP SEQUENCE IF EXISTS seq_risca_r_pag_non_propri;
DROP SEQUENCE IF EXISTS seq_risca_r_pagopa_lista_car_iuv;
DROP SEQUENCE IF EXISTS seq_risca_r_pagopa_lista_carico;
DROP SEQUENCE IF EXISTS seq_risca_r_pagopa_scomp_rich_iuv;
DROP SEQUENCE IF EXISTS seq_risca_r_pagopa_scomp_var_iuv;
DROP SEQUENCE IF EXISTS seq_risca_r_parametro_elabora;
DROP SEQUENCE IF EXISTS seq_risca_r_provvedimento;
DROP SEQUENCE IF EXISTS seq_risca_r_rata_sd;
DROP SEQUENCE IF EXISTS seq_risca_r_recapito;
DROP SEQUENCE IF EXISTS seq_risca_r_recapito_postel;
DROP SEQUENCE IF EXISTS seq_risca_r_registro_elabora;
DROP SEQUENCE IF EXISTS seq_risca_r_rimborso;
DROP SEQUENCE IF EXISTS seq_risca_r_riscossione_storia_titolare;
DROP SEQUENCE IF EXISTS seq_risca_r_riscossione_uso;
DROP SEQUENCE IF EXISTS seq_risca_r_ruolo;
DROP SEQUENCE IF EXISTS seq_risca_r_ruolo_soris_fr1;
DROP SEQUENCE IF EXISTS seq_risca_r_ruolo_soris_fr3;
DROP SEQUENCE IF EXISTS seq_risca_r_ruolo_soris_fr7;
DROP SEQUENCE IF EXISTS seq_risca_r_soggetto_delega;
DROP SEQUENCE IF EXISTS seq_risca_r_soll_dati_amministr;
DROP SEQUENCE IF EXISTS seq_risca_r_soll_dati_pagopa;
DROP SEQUENCE IF EXISTS seq_risca_r_soll_dati_titolare;
DROP SEQUENCE IF EXISTS seq_risca_r_soll_destinatari;
DROP SEQUENCE IF EXISTS seq_risca_r_soll_dett_vers;
DROP SEQUENCE IF EXISTS seq_risca_r_spedizione_acta;
DROP SEQUENCE IF EXISTS seq_risca_r_tipo_uso_regola;
DROP SEQUENCE IF EXISTS seq_risca_r_uso_ridaum;
DROP SEQUENCE IF EXISTS seq_risca_s_tracciamento;
DROP SEQUENCE IF EXISTS seq_risca_t_accertamento;
DROP SEQUENCE IF EXISTS seq_risca_t_delegato;
DROP SEQUENCE IF EXISTS seq_risca_t_elabora;
DROP SEQUENCE IF EXISTS seq_risca_t_file_450;
DROP SEQUENCE IF EXISTS seq_risca_t_file_poste;
DROP SEQUENCE IF EXISTS seq_risca_t_file_soris;
DROP SEQUENCE IF EXISTS seq_risca_t_gruppo_soggetto;
DROP SEQUENCE IF EXISTS seq_risca_t_immagine;
DROP SEQUENCE IF EXISTS seq_risca_t_invio_acta;
DROP SEQUENCE IF EXISTS seq_risca_t_iuv;
DROP SEQUENCE IF EXISTS seq_risca_t_lotto;
DROP SEQUENCE IF EXISTS seq_risca_t_pagamento;
DROP SEQUENCE IF EXISTS seq_risca_t_riscossione;
DROP SEQUENCE IF EXISTS seq_risca_t_soggetto;
DROP SEQUENCE IF EXISTS seq_risca_t_spedizione;
DROP SEQUENCE IF EXISTS seq_risca_t_stato_debitorio;
