/*******************************************************************************
 *  ========================LICENSE_START=================================
 *   
 *  Copyright (C) 2025 Regione Piemonte
 *   
 *  SPDX-FileCopyrightText: (C) Copyright 2025  Regione Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 *  =========================LICENSE_END==================================
 *******************************************************************************/
/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.19-SNAPSHOT).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package it.csi.risca.riscabesrv.business.be.helper.scriva.api;

import javax.servlet.http.HttpServletRequest;
import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.HeaderParam;
import javax.ws.rs.POST;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.HttpHeaders;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import javax.ws.rs.core.SecurityContext;

import org.springframework.web.bind.annotation.RequestBody;

import it.csi.risca.riscabesrv.business.be.helper.scriva.dto.SoggettoExtendedDTO;

@Path("/soggetti")
@Consumes({ MediaType.APPLICATION_JSON })
@Produces({ MediaType.APPLICATION_JSON })
public interface SoggettiApi {

    @GET 
	@Produces({ "application/json" })
    Response getSoggetti(@HeaderParam("X-Request-Auth") String xRequestAuth,
    		@HeaderParam("X-Request-Id") String xRequestId,
    		@QueryParam("id_soggetto") Long idSoggetto,
    		@QueryParam("codice_fiscale") String codiceFiscale,
    		@QueryParam("tipo_soggetto") String tipoSoggetto,
    		@QueryParam("cod_adempimento") String codAdempimento,
    		@QueryParam("codice_fiscale_impresa") String codiceFiscaleImpresa);

    @POST
    Response saveSoggetto(@RequestBody SoggettoExtendedDTO soggetto, @Context SecurityContext securityContext, @Context HttpHeaders httpHeaders, @Context HttpServletRequest httpRequest);

}
