/**
 * Enum che definisce i codici per i tipi ricerca morosita.
 */
export enum CodiciTipoRicercaMorosita {
  DA_ACCERTARE = 'RICMOR01',
  AVVISO_BONARIO_DA_SPEDIRE = 'RICMOR02',
  AVVISO_BONARIO_SPEDITO = 'RICMOR03',
  AVVISO_BONARIO_SCADUTO = 'RICMOR04',
  SOLLECITO_DI_PAGAMENTO_DA_SPEDIRE = 'RICMOR05',
  SOLLECITO_DI_PAGAMENTO_SPEDITO = 'RICMOR06',
  SOLLECITO_RATEIZZAZIONE_SCADUTI = 'RICMOR07',
  DA_INVIARE_A_RISCOSSIONE_COATTIVA = 'RICMOR08',
  RISCOSSIONE_COATTIVA = 'RICMOR09',
  NON_ACCERTATO = 'RICMOR10',
  RISCOSSIONE_COATTIVA_ANNULLATA = 'RICMOR11',
  FALLIMENTO = 'RICMOR12',
  DA_VERIFICARE = 'RICMOR13',
  RATEIZZAZIONE_PAGAMENTO_AUTORIZZATA = 'RICMOR14',
  CANONE_NON_ESIGIBILE = 'RICMOR15',
  CONCORDATO = 'RICMOR16',
}