/**
 * Interfaccia di supporto per la definizione delle chiavi per la gestione degli accessi agli elementi dell'app.
 */
interface IAccessoElementiAppKeys {
  PAGAMENTI: string;
  VERIFICHE: string;

  NUOVA_PRATICA_HOME: string;
  ELIMINA_SOGGETTO: string;
  ELIMINA_GRUPPO: string;
  NUOVO_SOGGETTO_CERCA: string;
  NUOVO_GRUPPO_HOME: string;
  NUOVO_GRUPPO_H_CERCA: string;
  INS_PRATICA_H_CERCA: string;
  POST_PUT_DEL_RISC: string;
  POST_PUT_DEL_SOGG: string;
  NUOVA_PRATICA_SOGG: string;
  NUOVA_PRATICA_GRUPPO: string;
  PAGINA_DATI_AMM: string;
  PAGINA_DATI_ANAG: string;
  PAGINA_DATI_TECNICI: string;
  DETTAGLIO_SOGGETTO: string;
  ANNULLA_SOGGETTO: string;
  SALVA_SOGGETTO: string;
  DETTAGLIO_GRUPPO: string;
  ANNULLA_GRUPPO: string;
  SALVA_GRUPPO: string;
  ANNULLA_PRATICA: string;
  SALVA_PRATICA: string;

  SALVA_INDIRIZZO_SPED: string;
  DETTAGLIO_IND_SPED: string;

  VERSAMENTI: string;
  RIMBORSI: string;
  ACCERTAMENTI: string;
  STATO_DEBITORIO: string;
  INSERIMENTO_STATO_DEBITORIO: string;
  NAP: string;
  CALCOLA_INTERESSI: string;

  ESPORTA_DATI: string;

  SPEDIZIONI: string;
  DET_STATO_DEB: string;
  DET_PAGAMENTI: string;
  PAGINA_DOC_ALLEGATI: string;

  CONFIGURAZIONI: string;

  PAGINA_CANONI: string;
  CREA_ANNUALITA: string;

  TASSI_DI_INTERESSI_H: string;
  PARAMETRI_DILAZIONE_H: string;
  ALTRI_PARAMETRI_H: string;

  PAG_TASSI_INTERESSE: string;
}

/**
 * Oggetto che definisce la mappatura delle chiavi per l'accesso agli elementi dell'app.
 */
export const AccessoElementiAppKeyConsts: IAccessoElementiAppKeys = {
  PAGAMENTI: 'PAGAMENTI',
  VERIFICHE: 'VERIFICHE',

  NUOVA_PRATICA_HOME: 'NUOVA_PRATICA_HOME',
  ELIMINA_SOGGETTO: 'ELIMINA_SOGGETTO',
  ELIMINA_GRUPPO: 'ELIMINA_GRUPPO',
  NUOVO_SOGGETTO_CERCA: 'NUOVO_SOGGETTO_CERCA',
  NUOVO_GRUPPO_HOME: 'NUOVO_GRUPPO_HOME',
  NUOVO_GRUPPO_H_CERCA: 'NUOVO_GRUPPO_H_CERCA',
  INS_PRATICA_H_CERCA: 'INS_PRATICA_H_CERCA',
  POST_PUT_DEL_RISC: 'POST_PUT_DEL_RISC',
  POST_PUT_DEL_SOGG: 'POST_PUT_DEL_SOGG',
  NUOVA_PRATICA_SOGG: 'NUOVA_PRATICA_SOGG',
  NUOVA_PRATICA_GRUPPO: 'NUOVA_PRATICA_GRUPPO',
  PAGINA_DATI_AMM: 'PAGINA_DATI_AMM',
  PAGINA_DATI_ANAG: 'PAGINA_DATI_ANAG',
  PAGINA_DATI_TECNICI: 'PAGINA_DATI_TECNICI',
  DETTAGLIO_SOGGETTO: 'DETTAGLIO_SOGGETTO',
  ANNULLA_SOGGETTO: 'ANNULLA_SOGGETTO',
  SALVA_SOGGETTO: 'SALVA_SOGGETTO',
  DETTAGLIO_GRUPPO: 'DETTAGLIO_GRUPPO',
  ANNULLA_GRUPPO: 'ANNULLA_GRUPPO',
  SALVA_GRUPPO: 'SALVA_GRUPPO',
  ANNULLA_PRATICA: 'ANNULLA_PRATICA',
  SALVA_PRATICA: 'SALVA_PRATICA',

  SALVA_INDIRIZZO_SPED: 'SALVA_INDIRIZZO_SPED',
  DETTAGLIO_IND_SPED: 'DETTAGLIO_IND_SPED',

  VERSAMENTI: 'VERSAMENTI',
  RIMBORSI: 'RIMBORSI',
  ACCERTAMENTI: 'ACCERTAMENTI',
  STATO_DEBITORIO: 'STATO_DEBITORIO',
  INSERIMENTO_STATO_DEBITORIO: 'INSERT_STATO_DEB',
  NAP: 'NAP',
  CALCOLA_INTERESSI: 'CALCOLA_INTERESSI',

  ESPORTA_DATI: 'EXPORT_DATI',

  SPEDIZIONI: 'SPEDIZIONI',
  DET_STATO_DEB: 'DET_STATO_DEB',
  DET_PAGAMENTI: 'DET_PAGAMENTI',
  PAGINA_DOC_ALLEGATI: 'PAGINA_DOC_ALLEGATI',

  CONFIGURAZIONI: 'CONFIGURAZIONI',

  PAGINA_CANONI: 'PAGINA_CANONI',
  CREA_ANNUALITA: 'CREA_ANNUALITA',

  TASSI_DI_INTERESSI_H: '', // Per il momento non ci sono chiavi, sono state predisposte per possibili implementazioni
  PARAMETRI_DILAZIONE_H: '', // Per il momento non ci sono chiavi, sono state predisposte per possibili implementazioni
  ALTRI_PARAMETRI_H: '', // Per il momento non ci sono chiavi, sono state predisposte per possibili implementazioni

  PAG_TASSI_INTERESSE: 'PAG_TASSI_INTERESSE',
};
