/*******************************************************************************
 *  ========================LICENSE_START=================================
 *   
 *  Copyright (C) 2025 Regione Piemonte
 *   
 *  SPDX-FileCopyrightText: (C) Copyright 2025  Regione Piemonte
 *  SPDX-License-Identifier: EUPL-1.2
 *  =========================LICENSE_END==================================
 *******************************************************************************/
/**
 * ObjectServicePort_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package it.csi.risca.riscabesrv.util.actaobject;

public interface ObjectServicePort_PortType extends java.rmi.Remote {
    public it.csi.risca.riscabesrv.util.actaobject.ObjectIdType createFolder(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, java.lang.String typeId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.PropertiesType properties, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType folderId) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.ObjectResponseType getProperties(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType objectId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.ObjectResponseType[] getPropertiesMassive(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType[] identifiers, it.csi.risca.riscabesrv.util.actaobject.PropertyFilterType filter) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.ObjectIdType createDocument(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, java.lang.String typeId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.PropertiesType properties, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType folderId, it.csi.risca.riscabesrv.util.actaobject.AcarisContentStreamType contentStream) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.ObjectIdType createAssociativeDocument(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, java.lang.String typeId, java.lang.String associativeObjectTypeId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.PropertiesType properties, it.csi.risca.riscabesrv.util.actaobject.PropertiesType associativeObjectProperties, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType folderId, it.csi.risca.riscabesrv.util.actaobject.AcarisContentStreamType contentStream) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.ObjectIdType createRelationship(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, java.lang.String typeId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.PropertiesType properties, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType sourceObjectId, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType targetObjectId) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.AcarisContentStreamType[] getContentStream(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType documentId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, java.lang.String streamId) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.SimpleResponseType addRenditionStream(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType documentId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.ChangeTokenType changeToken, java.lang.String streamId, it.csi.risca.riscabesrv.util.actaobject.AcarisContentStreamType[] contentStream) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.SimpleResponseType updateProperties(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType objectId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.ChangeTokenType changeToken, it.csi.risca.riscabesrv.util.actaobject.PropertyType[] properties) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.SimpleResponseType setContentStream(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType documentId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.ChangeTokenType changeToken, it.csi.risca.riscabesrv.util.actaobject.AcarisContentStreamType contentStream) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.PagingResponseType query(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.QueryableObjectType target, it.csi.risca.riscabesrv.util.actaobject.PropertyFilterType filter, it.csi.risca.riscabesrv.util.actaobject.QueryConditionType[] criteria, it.csi.risca.riscabesrv.util.actaobject.NavigationConditionInfoType navigationLimits, java.lang.Integer maxItems, java.lang.Integer skipCount) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public void moveDocument(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId, it.csi.risca.riscabesrv.util.actaobject.holders.ObjectIdTypeHolder associativeObjectId, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType sourceFolderId, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType targetFolderId, it.csi.risca.riscabesrv.util.actaobject.PropertiesType associativeProperties) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
    public it.csi.risca.riscabesrv.util.actaobject.SimpleResponseType closeFolder(it.csi.risca.riscabesrv.util.actaobject.ObjectIdType repositoryId, it.csi.risca.riscabesrv.util.actaobject.ObjectIdType objectId, it.csi.risca.riscabesrv.util.actaobject.PrincipalIdType principalId) throws java.rmi.RemoteException, it.csi.risca.riscabesrv.util.actaobject.AcarisFaultType;
}
